#! /bin/bash -xe

WORKSPACE=$1

cd ${WORKSPACE}

export ERL_LIBS=~/erlide_tools:${WORKSPACE}

cd org.erlide.kernel.common
~/erlide_tools/rebar/rebar compile eunit -vv
cd ..

cd org.erlide.kernel.ide
~/erlide_tools/rebar/rebar compile eunit -vv
cd ..

# iconv -f ISO-8859-1 -t UTF-8 $OUTPUT/junit0.xml > $OUTPUT/junit.xml

