#! /bin/bash

WORKSPACE=$1
ERLANG_HOME=$2
OUTPUT=$WORKSPACE/$3

if [ -z "$4" ] ; then
  TEST=kernel
else
  TEST="erlide_$4"
fi

mkdir -p $OUTPUT

cd ${WORKSPACE}

${ERLANG_HOME}/bin/erl -pa ${WORKSPACE}/org.erlide.kernel.builder/ebin -pa ${WORKSPACE}/org.erlide.kernel.debugger/ebin -pa ${WORKSPACE}/org.erlide.kernel.ide/ebin -pa ${WORKSPACE}/org.erlide.kernel.tests/ebin -pa ${WORKSPACE}/org.erlide.kernel.common/ebin -eval "eunit:test(${TEST}_tests, [{report,{eunit_surefire,[{dir,\"$OUTPUT\"}]}}]),init:stop()." -noshell

