#! /bin/bash

# arguments:
# WORKSPACE - location of the source code root
# JAVA_HOME - location of JDK
# erlang_R12 - location of R12
# erlang_R13 - location of R13 
# BUCKMINSTER - location of the Bucky installation
# TARGET - location of eclipse installation that defines the target system 

WORKSPACE=$1
JAVA_HOME=$2
erlang_R12=$3
erlang_R13=$4
BUCKMINSTER=$5
TARGET=$6 

SITE_PRJ=org.erlide.site

cp ${SITE_PRJ}/erl.epf ${SITE_PRJ}/_erl.epf
sed -e "s%#{erlang_R12}%${erlang_R12}%g" -e "s%#{erlang_R13}%${erlang_R13}%g" ${SITE_PRJ}/erl.epf > ${SITE_PRJ}/_erl.epf

cp ${SITE_PRJ}/bucky_cmds ${SITE_PRJ}/_bucky_cmds
sed -e "s%#{WORKSPACE}%${WORKSPACE}%g" -e "s%#{TARGET}%${TARGET}%g" -e "s%#{JAVA_HOME}%${JAVA_HOME}%g" -e "s%#{SITE_PRJ}%${SITE_PRJ}%g" ${SITE_PRJ}/bucky_cmds > ${SITE_PRJ}/_bucky_cmds

cp ${SITE_PRJ}/buckminster.properties ${SITE_PRJ}/_buckminster.properties
echo "buckminster.output.root=${WORKSPACE}/buckminster.output" >> ${SITE_PRJ}/_buckminster.properties
echo "buckminster.temp.root=${WORKSPACE}/buckminster.temp" >> ${SITE_PRJ}/_buckminster.properties
 
#LAUNCHER=${BUCKMINSTER}/plugins/org.eclipse.equinox.launcher_1.0.201.R35x_v20090715.jar 
LAUNCHER=`find -L ${BUCKMINSTER}/plugins/ -name "org.eclipse.equinox.launcher_*.jar" -type f | head -n 1` 
 
${JAVA_HOME}/bin/java -jar ${LAUNCHER} -application org.eclipse.buckminster.cmdline.headless -data ${WORKSPACE} --loglevel info -S ${WORKSPACE}/${SITE_PRJ}/_bucky_cmds

