#! /bin/bash

# adds contents of $remote_site to $new_site

#ECLIPSE=/proj/uz/erlide/eclipse352/eclipse
#remote_site=http://erlide.org/update
#new_site=file:///home/eshadeln/.hudson/jobs/bucky/workspace/buckminster.output/org.erlide.site_1.0.0-eclipse.feature/site.p2

ECLIPSE=$1
remote_site=$2
new_site=$3

echo Mirroring metadata for $remote_site
java -jar $ECLIPSE/plugins/org.eclipse.equinox.launcher_*.jar -application org.eclipse.equinox.p2.metadata.repository.mirrorApplication -source $remote_site -destination $new_site -verbose 
#-ignoreErrors
 
echo Mirroring artifacts for $remote_site
java -jar $ECLIPSE/plugins/org.eclipse.equinox.launcher_*.jar -application org.eclipse.equinox.p2.artifact.repository.mirrorApplication -source $remote_site -destination $new_site -verbose 
#-ignoreErrors

