package org.erlide.cover.ui.views.util;

import org.eclipse.xtend2.lib.StringConcatenation;
import org.erlide.cover.views.model.ICoverageObject;

@SuppressWarnings("all")
public class ReportTemplate {
    private final ICoverageObject obj;

    private final String date;

    private final String type;

    public ReportTemplate(final ICoverageObject obj, final String date,
            final String type) {
        this.obj = obj;
        this.date = date;
        this.type = type;
    }

    public String getReport(final boolean relative) {
        final StringConcatenation _builder = new StringConcatenation();
        _builder.append("<html>");
        _builder.newLine();
        _builder.append("<head>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<style type=\"text/css\">");
        _builder.newLine();
        _builder.append("        ");
        final CharSequence _css = getCss();
        _builder.append(_css, "        ");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("</style>");
        _builder.newLine();
        _builder.append("</head>");
        _builder.newLine();
        _builder.append("<body>");
        _builder.newLine();
        _builder.append(
                "<div class=\"title\">Cover plugin for ErlIde - coverage report (generated at ");
        _builder.append(date);
        _builder.append(") </div>");
        _builder.newLineIfNotEmpty();
        _builder.append("<br/>");
        _builder.newLine();
        _builder.append("<h2>Coverage summary for: ");
        final String _label = obj.getLabel();
        _builder.append(_label);
        _builder.append(" </h2>");
        _builder.newLineIfNotEmpty();
        _builder.append("<table class>");
        _builder.newLine();
        _builder.append("<tr>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<th>Name</th>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<th class=\"total\">Total Lines</th>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<th class=\"covered\">Covered Lines</th>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<th class=\"percentage\">Coverage %</th>");
        _builder.newLine();
        _builder.append("</tr>");
        _builder.newLine();
        _builder.append("<tr>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<td><b>");
        final String _label_1 = obj.getLabel();
        _builder.append(_label_1, "    ");
        _builder.append("</b></td>");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("<td>");
        final int _linesCount = obj.getLinesCount();
        _builder.append(_linesCount, "    ");
        _builder.append("</td>");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("<td>");
        final int _coverCount = obj.getCoverCount();
        _builder.append(_coverCount, "    ");
        _builder.append("</td>");
        _builder.newLineIfNotEmpty();
        _builder.append("    ");
        _builder.append("<td>");
        final String _percentageStringified = obj.getPercentageStringified();
        _builder.append(_percentageStringified, "    ");
        _builder.append("</td>");
        _builder.newLineIfNotEmpty();
        _builder.append("</tr>");
        _builder.newLine();
        _builder.append("</table>");
        _builder.newLine();
        _builder.append("<h2>Coverage breakdown by ");
        _builder.append(type);
        _builder.append(" </h2>");
        _builder.newLineIfNotEmpty();
        _builder.append("<table>");
        _builder.newLine();
        _builder.append("<tr>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<th>Name</th>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<th class=\"total\">Total Lines</th>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<th class=\"covered\">Covered Lines</th>");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("<th class=\"percentage\">Coverage %</th>");
        _builder.newLine();
        _builder.append("</tr>");
        _builder.newLine();
        {
            final ICoverageObject[] _children = obj.getChildren();
            for (final ICoverageObject child : _children) {
                _builder.append("  ");
                _builder.append("<tr>");
                _builder.newLine();
                _builder.append("  ");
                _builder.append("  ");
                _builder.append("<td><a href=\"");
                String _xifexpression = null;
                if (relative) {
                    _xifexpression = child.getRelativePath();
                } else {
                    _xifexpression = child.getHtmlPath();
                }
                _builder.append(_xifexpression, "    ");
                _builder.append("\">");
                final String _label_2 = child.getLabel();
                _builder.append(_label_2, "    ");
                _builder.append("</a></td>");
                _builder.newLineIfNotEmpty();
                _builder.append("  ");
                _builder.append("  ");
                _builder.append("<td>");
                final int _linesCount_1 = child.getLinesCount();
                _builder.append(_linesCount_1, "    ");
                _builder.append("</td>");
                _builder.newLineIfNotEmpty();
                _builder.append("  ");
                _builder.append("  ");
                _builder.append("<td>");
                final int _coverCount_1 = child.getCoverCount();
                _builder.append(_coverCount_1, "    ");
                _builder.append("</td>");
                _builder.newLineIfNotEmpty();
                _builder.append("  ");
                _builder.append("  ");
                _builder.append("<td>");
                final String _percentageStringified_1 = child.getPercentageStringified();
                _builder.append(_percentageStringified_1, "    ");
                _builder.append("</td>");
                _builder.newLineIfNotEmpty();
                _builder.append("  ");
                _builder.append("</tr>");
                _builder.newLine();
            }
        }
        _builder.append("</table>");
        _builder.newLine();
        _builder.append("<br/>");
        _builder.newLine();
        _builder.append("<br/>");
        _builder.newLine();
        _builder.append("<br/>");
        _builder.newLine();
        _builder.append(
                "<div class=\"footer\">Cover plugin for ErlIde 0.2.0 &copy Erlang Solutions</div>");
        _builder.newLine();
        _builder.append("</body>");
        _builder.newLine();
        _builder.append("</html>");
        _builder.newLine();
        return _builder.toString();
    }

    public CharSequence getCss() {
        final StringConcatenation _builder = new StringConcatenation();
        _builder.append("body {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("font-size: 12px:");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("h2 {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("font-size: 14px;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("div.title {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("border: solid #333333 2px;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("font-size: 11px;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("color: #EEEEEE;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("text-align: center;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("background-color: #772222;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("padding: 4px;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("div.footer {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("border: solid #333333 2px;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("font-size: 11px;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("color: #5599FF;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("text-align: center;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("background-color: #772222;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("padding: 3px;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("table {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("width: 100%;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("border: solid #000000 1px;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("border-collapse: collapse;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("font-size: 12px;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("table-layout: fixed;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("td {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("border: solid #000000 1px;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("padding: 2px 5px 2px 5px;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("a, a:link {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("text-decoration: none;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("font-weight: bold;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("color: #1144CC;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("a:visited {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("color: #112255;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("a:hover {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("text-decoration: underline;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("th {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("border: solid #000000 1px;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("background-color: #AA5555;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("color: #EEEEEE;");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("padding: 3px;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("th.total {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("width: 120px;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("th.covered {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("width: 120px;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        _builder.newLine();
        _builder.append("th.percentage {");
        _builder.newLine();
        _builder.append("    ");
        _builder.append("width: 160px;");
        _builder.newLine();
        _builder.append("}");
        _builder.newLine();
        return _builder;
    }
}
