%% Description: References used for searches, generated by erlide_noparse
%% Author: jakob (jakobce at g mail dot com)
%% Created: 21 mar 2010

-define(SEARCH_SERVER, erlide_search_server).

-record(ref, {data, offset, length, function, arity, clause, sub_clause}).
%% function is a {F, A} tuple

-record(external_call, {module, function, arity}).
-record(local_call, {function, arity}).
-record(macro_ref, {macro}).
-record(record_ref, {record}).

%% förslag på hur scanner, parser och search jobbar ihop:
%%
%%
%% Filer        Process                          Modul
%%
%% .scan        <scannernamn>  <- läser/skriver  erlide_scanner_server.erl   
%%
%% .noparse     - ingen -     <- läser          erlide_noparse.erl   skriver -> .refs
%%
%% .refs  <-läser erlide_search_server    erlide_search_server.erl
%%
%% scanner-server talar om för search-server när buffert stängs (listener av ngt slag?)
%% noparse uppdaterar search-server när en buffert parsas om
%% noparse skapar .refs-fil om den ska skapa .noparse-fil

%% editorbuffert
%% - alltid i scan
%% - alltid i parse (? ingen process än, bara modell på java-sidan)
%% - ev. i search (LRU)
%%
%% .erl-fil ej i editor
%% - aldrig i scan
%% - ev. i parse (LRU ? ingen process än, ev modell på java-sidan)
%% - ev. i search (LRU)
%%
%% search hämtar data
%% - alltid via noparse, som ger {read, Refsfile} eller {refs, [...]} tillbaka

%% cache-filer bör göras om!
%% skapa endast vid read och write
%% håll scanner i minnet omm editorbuffert finns
