%% Description: References used for searches, generated by erlide_noparse
%% Author: jakob (jakobce at g mail dot com)
%% Created: 21 mar 2010

-record(external_call, {module, function, arity, offset, length}).
-record(local_call, {function, arity, offset, length}).
-record(macro_ref, {macro, offset, length}).
-record(record_ref, {record, offset, length}).
