#!/bin/bash -xe

SOURCE_JOB=$1
SOURCE_ID=$2
SITE_TYPE=$3 # master, beta, nightly
DESTINATION=$4
USER=$5

IN=${WORKSPACE}/buildroot/buckminster.output/org.erlide.site_1.0.0-eclipse.feature/site.p2
OUT=${ERLIDE}/update_sites/${SOURCE_JOB}_${SOURCE_ID}

rm -rf ${OUT}/*
mkdir -p $OUT

# mirror job output to OUT
bash -ex org.erlide.releng/mirror_p2 ${JAVA_HOME} ${ECLIPSE} file://${IN} file://${OUT}
if [ $? != 0 ]; then
    exit $?
fi

pushd $IN
zip -r $OUT/org.erlide.site.zip *
popd

# if DEST=path, copy OUT to DEST
if [ -d "${DESTINATION}" ]; then
    # rm -rf ${DESTINATION}/*  # TODO option to clean?
    cp -r ${OUT}/* ${DESTINATION}
fi

if [ $? != 0 ]; then
    exit $?
fi

if [ -n "$SITE_TYPE" ]; then
    cd ${ERLIDE}/update_sites
    rm $SITE_TYPE
    ln -s $OUT $SITE_TYPE
fi



